### ISSUE TITLE
Unable to verify email

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/amphora#4]
Trying to confirm my email in response to the "Please Confirm Email Address" email that was sent as part of the account creation process.  When I click on the button or paste the url provided, I get: "Uh oh!  An error occurred while processing your request."  I tried it both last night as well as today.

**Comment by xtellurian** [comment]
The server is unable to validate the email confirmation token, and is throwing an error. We're looking into a fix, and should have an estimate for you soon.

**Comment by xtellurian** [comment]
The issue was that our email provider was encoding the `code` in a way that our application couldn't understand.

We've attempted to resolve the issue by using a much more basic Email template. It doesn't look as nice, but it does seem to work.

@rob-yerc you'll need to resend the confirmation email. You can do that in your [manage profile](https://beta.amphoradata.com/Profiles/Account/Manage) page.

**Comment by rob-yerc** [comment]
In profile settings, I resent the confirmation email.  Clicking on the button in the new email worked just fine.
